### ISSUE TITLE
Single pages not shown when creating an internal link with Redactor

### ISSUE THREAD

**Issue by shoored** [verbb/expanded-singles#6] opened 2017-10-30 14:06 UTC
When I enable the plugin and set 'Expanded Singles' on, whenever I want to link to a Single Entry page from within Redactor, no Singles are shown in the Redactor link-dialog. Only Channel or Structures.

When I disable the plugin, the Single entries are again shown in the Redactor link-dialog.

**Comment by lukeyouell** [comment] 2017-11-24 12:02
I've just noticed this too

**Comment by svenjungnickel** [comment] 2017-11-28 04:02
Thank @shoored and @lukeyouell for the issue. I fixed it in the latest version for [craft-2](https://github.com/verbb/expanded-singles/archive/craft-2.zip) and [craft3](https://github.com/verbb/expanded-singles/archive/craft-3.zip). Can you confirm that the issue is fixed? Thanks.

**Comment by lukeyouell** [comment] 2017-11-29 10:10
hey @svenjungnickel it now adds 'Singles' to the bottom of the list, this doesn't match the behaviour expected from the plugin and in my opinion could confuse clients. Unless I'm missing something?

**Comment by svenjungnickel** [comment] 2017-11-29 10:49
Hey @lukeyouell. Which version are you using? Craft 2 or Craft 3? If you're using the Craft 3 version, did you install it via composer using the dev tag `composer require verbb/cp-nav:dev-craft-3`?

**Comment by lukeyouell** [comment] 2017-11-29 10:54
@svenjungnickel I'm using the latest version of Craft 2

**Comment by svenjungnickel** [comment] 2017-11-29 11:01
Just tested it. It appears for me at the top of the modal view. Can you provide some more details @lukeyouell, maybe a screenshot, config settings which differ from the default etc.?

**Comment by lukeyouell** [comment] 2017-11-29 11:05
There are no config settings that differ from default. I've attached a screenshot displaying the singles at the bottom of the list.

<img width="324" alt="screen shot 2017-11-29 at 11 03 47" src="https://user-images.githubusercontent.com/24975058/33372227-222e66ea-d4f5-11e7-88bf-e7b0ca11d7f8.png">

**Comment by svenjungnickel** [comment] 2017-11-29 11:09
Thanks. Seems a bit odd. But I will dive into it and try to figure out what that occurs. I will come back to you.

**Comment by shoored** [comment] 2017-11-29 11:13
Thanks @svenjungnickel for the fix! This works correctly on my local Craft2 environment.

![image](https://user-images.githubusercontent.com/26165948/33372547-b60fed9e-d4fe-11e7-9e71-ad63919526d3.png)

**Comment by svenjungnickel** [comment] 2017-11-29 11:19
@shoored thanks for your reply. That shows me that it worked at least for some one :D 
@lukeyouell do you have other plugins installed which adjust the entry selection modal? Which Craft2 version are you using?

**Comment by engram-design** [comment] 2017-11-30 02:49
@shoored @lukeyouell Just chiming in here after a decent amount of diving into how things are working (or not working!). ~~Prefacing this by saying this is all working correctly in Craft 3~~.

In Craft 2, the available sections are prepared in its own private function, which check to see if sections have URLs. If entries don't have a URL, you obviously shouldn't be able to link to them. However, this is overriding the default entry index behaviour, and you'll notice your channel/structure headings aren't even being shown on the modal entry selector in a Redactor field.

After much investigation, its sad to say there is nothing we can do about this in Craft 2, short of getting P&T to change their code for the Rich Text field to accomodate for us. As such, we've had to disable Expanded Singles' functionality in the context of a modal window - when in use through Redactor, or an Entry select field. We can't have one working without negatively affecting the other.

Sorry there's no real solution to this, but we argue having your singles available to select (even if under the 'Singles' menu), is better than not being able to select them at all. We'll look at creating a PR to Craft 2 and see how we go with coming up with a solution...

**Comment by engram-design** [comment] 2018-02-12 02:54
This has been fixed in the latest master for Craft 2. Its not really possible to fix this in Craft 2 I'm afraid. Closing for now.

**Closed by engram-design** 2018-02-12 02:54 UTC
Labels: wontfix
